<a href="https://colab.research.google.com/github/eeee-day/hongong_data/blob/main/%ED%98%BC%EA%B3%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%B1%95%ED%84%B01_%EC%BD%94%EB%9E%A9%EC%97%90%EC%84%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import gdown
gdown.download('https://bit.ly/3eecMKZ','남산도서관 장서 대출목록 (2021년 04월).csv', quiet=False)

Downloading...
From: https://bit.ly/3eecMKZ
To: /content/남산도서관 장서 대출목록 (2021년 04월).csv
100%|██████████| 58.1M/58.1M [00:00<00:00, 61.4MB/s]

'남산도서관 장서 대출목록 (2021년 04월).csv'

In [7]:
import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv', mode = 'rb') as f: #binary 읽기모드(인코딩 형식에 상관없이 파일 오픈 가능)로 파일 오픈
  d=f.readline()
print(chardet.detect(d)) #chardet.detect()함수를 사용하여 인코딩 방식 파악하기

{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [9]:
with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR')as f:
  print (f.readline())
  print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","인공지능과 흙","김동훈 지음","민음사","2021","9788937444319","","","","","1","0","2021-03-19",

In [13]:
#csv 파일을 데이터프레임으로 읽기 : read_csv()함수 사용하기
import pandas as pd #pandas패키지를 pd로 import
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR',low_memory=False)
#low_memory=False -> 데이터프레임의 한 column에 여러 type의 데이터가 섞여있을 경우 나타나는 오류를 출력하지 않게 함

In [15]:
df.head() #데이터프레임의 상위 5행 확인
#unnamed:13 -> csv파일의 각 라인 끝에 (,)로 인해 열이 하나 더 있다고 인식하여 생긴 것

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

*   read_csv() : (,)콤마로 열 구분
*   read_table() : (\t)탭으로 열 구분

In [16]:
df.to_csv('ns_202104.csv')#데이터프레임을 csv파일로 저장

In [18]:
with open('ns_202104.csv') as f:
  for i in range(3):
    print(f.readline(), end="") #end=""을 이용해 줄바꿈 문자 출력하지 않음

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,

In [21]:
ns_df=pd.read_csv('ns_202104.csv',index_col=0,low_memory="false")
ns_df.head()
#unnamed: 0 -> 위에서 생성한 데이터프레임의 index까지 저장하여 열로 인식한 것 .
#따라서, index_col=0을 이용해 0번째 열이 index임을 알려줌

<ipython-input-21-a22a66edffa2>:1: DtypeWarning: Columns (6,7,10) have mixed types. Specify dtype option on import or set low_memory=False.
  ns_df=pd.read_csv('ns_202104.csv',index_col=0,low_memory="false")

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

*   df.to_csv('ns_202104.csv',index=False) 를 통해 index 매개변수를 저장하지 않는 방법도 있음
*   ns_df.to_excel('ns_202104.xlsx',index=False, engine='xlsxwriter') 를 통해 excel파일로도 저장 가능